package:
  name: readtagger
  version: {{ GIT_DESCRIBE_TAG| replace('v', '', 1) }}

source:
  git_url: ../../

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0)}}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python
    - pip
    - setuptools

  run:
    - backports.functools_lru_cache  # [not py3k]
    - backports.tempfile  # [not py3k]
    - bcbiogff
    - biopython
    - bwa
    - cached-property
    - cap3
    - click
    - contextlib2
    - futures  # [not py3k]
    - matplotlib
    - multiprocessing-logging
    - pandas
    - pysam >=0.14
    - python-edlib
    - scipy
    - six

test:
  # Python imports
  imports:
    - readtagger

  commands:
    - readtagger --help
    - allow_dovetailing --help
    - add_matesequence --help
    - findcluster --help
    - plot_coverage --help

about:
  home: https://github.com/bardin-lab/readtagger
  license: MIT
  summary: 'Tags reads in BAM files based on alignments in additional BAM files.'
  license_family: MIT
